language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install pillow
script: # run tests
  - "git clone --branch Project-1-Data-Processing-Application https://github.com/GreyFox-Z/AppSec-2020/edit/Project-1-Data-Processing-Application.git"
  - "sudo ./Image_Size_Modifier.py Test.jpg"
  - nosetests --with-coverage
branches:
  only:
    - Project-1-Data-Processing-Application
after_success:
  - codecov # submit coverage
