language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install pillow
script: # run tests
  - python Main.py
after_success:
  - codecov # submit coverage
